name: 'Action to get environment'
outputs:
  environment:
    value: ${{ steps.setup.outputs.environment }}
    
runs:
  using: 'composite'
  steps:
      - name: Get Environment  
        id: setup
        shell: bash
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            echo "environment=dev" >> $GITHUB_OUTPUT

          elif [[ "${{ github.ref_name }}" == "main" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            echo "environment=prd" >> $GITHUB_OUTPUT

          elif [[ "${{ github.ref_name }}" == "release" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            echo "environment=pre" >> $GITHUB_OUTPUT

          elif [[ "${{ github.ref_name }}" == "quality" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            echo "environment=qa" >> $GITHUB_OUTPUT

          elif [[ "${{ github.ref_name }}" == "test" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            echo "environment=test" >> $GITHUB_OUTPUT     
                   
          else
            echo "Environment not defined for the branch ${{ github.ref_name }}"
          fi