name: 'Action to get environment'
inputs:
  composer_version:
    value: 2.6.4
outputs:
  deploy-env:
    value: ${{ steps.setup.outputs.deploy-env }}
    
runs:
  using: 'composite'
  steps:
      - name: Get Environment  
        id: setup
        shell: bash
        run: |
          if [[ "${{ startsWith(github.ref_name, 'develop') }}" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            DEPLOY_ENV="dev"

          elif [[ "${{ github.ref_name }}" == "main" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            DEPLOY_ENV="prd"

          elif [[ "${{ startsWith(github.ref_name, 'release') }}" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            DEPLOY_ENV="pre"

          elif [[ "${{ startsWith(github.ref_name, 'quality') }}" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            DEPLOY_ENV="qa"

          elif [[ "${{ startsWith(github.ref_name, 'test') }}" ]]; 
          then
            echo "Branch is ${{ github.ref_name }}"
            DEPLOY_ENV="test"   
                   
          else
            echo "Environment not defined for the branch ${{ github.ref_name }}"
            DEPLOY_ENV=""
          fi
          echo "deploy-env=$DEPLOY_ENV" >>"$GITHUB_OUTPUT"
          
       - name: Force Failure
         shell: bash
         run: |
           if [[ -z "${{ steps.setup.outputs.environment }}" ]]; then
               exit 1
           fi
