name: Deployment
#https://github.com/orgs/community/discussions/38178
on:
  push:
    branches:
      - develop
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'develop' }}
    steps:
      - name: deploy
        shell: bash
        run: |
          echo "${{ vars.FOO }}"
