name: Deployment
#https://github.com/orgs/community/discussions/38178
#https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setup.outputs.environment }}
    steps:
      - name: Check branch and set env variable
        id: setup
        uses: poc-gh-actions/testing-environment-gh@main
          
  deployment:
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.environment ! null }}
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    steps:
      - name: deploy
        shell: bash
        run: |
          echo "${{ vars.FOO }}"