name: Deployment
#https://github.com/orgs/community/discussions/38178
#https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#https://docs.github.com/en/actions/learn-github-actions/expressions
on:
  workflow_dispatch:

env:
  NODE_VERSION: "${{ vars.FOO }}"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      deploy-env: ${{ steps.setup.outputs.deploy-env }}
    steps:
      - name: Check branch and set env variable
        id: setup
        uses: poc-gh-actions/testing-environment-gh@main
          
  deployment:
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.deploy-env != null }}
    needs: setup
    environment: ${{ needs.setup.outputs.deploy-env }}
    steps:
      - name: deploy
        shell: bash
        run: |
          echo "${{ vars.FOO }}"
          echo "${{ env.NODE_VERSION }}"
