name: Deployment

on:
  push:
    branches:
      - develop
env:
  ambiente: "develop"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ env.ambiente }}
    steps:
      - name: deploy
        shell: bash
        run: |
          echo "${{ vars.FOO }}"
